### ISSUE TITLE
separate deployments for create & updates 

### ISSUE THREAD

**Issue by raj-patel** [rackerlabs/rs-heat-docs#14]
It may be helpful to make the first deployment execute only on create and other deployment on update. Also, add a note after stack create to tell users how to verify the deployment was run. Same goes for  stack update.

**Comment by rs-randallburt** [comment]
Which document and section?

**Comment by raj-patel** [comment]
https://github.com/rackerlabs/rs-heat-docs/blob/master/generic-software-config.rst. Under resources section there are 2 software deployment 'deployment' and 'other deployment'.

**Comment by rs-randallburt** [comment]
That would change the deployment section quite a bit. I suggest we create a new document discussing the actions section of a `OS::Heat::SoftwareDeployment` resource so we can show how one deployment can trigger on a create, another one on an update, and yet another delete (most interesting IMO) .

In the meantime, I suggest we either get rid of the second deployment since it seems to be a bit confusing and distracts from the goal of this document (very basic intro to software config).

**Comment by raj-patel** [comment]
I agree

**Comment by rs-randallburt** [comment]
Fixed the basic doc and template and added issue for creating new doc.
